const SCHEMA_EXPORT_TYPE_STRING = 'string'
const SCHEMA_EXPORT_TYPE_AST = 'ast'
const SCHEMA_EXPORT_TYPE_EXECUTABLE = 'executable'

module.exports = {
  SCHEMA_EXPORT_TYPE_AST,
  SCHEMA_EXPORT_TYPE_EXECUTABLE,
  SCHEMA_EXPORT_TYPE_STRING
}
